logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


cloud:
  aws:
    credentials:
      access-key: AKIAY6Z7EA6Y5R66ELJ3
      secret-key: 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
    s3:
      bucket: main22
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://main.cfjpwofewd2x.ap-northeast-2.rds.amazonaws.com:13306/main?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
#    username: admin
#    password: admin123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 374180078488-v6mh6ruhpsr5ja2vnmghslqvf28jb2mg.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
#          Kakao:
#            client-id: 2badaf984a50ed7e3b8f83534a70c397
#            client-secret: <your secret>
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST
#            client-name: Kakao
#            scope:
#              - profile
#              - account_email

#  redis:
#    host: localhost  # 배포 시 ec2 주소 사용
#    port: 6379

jwt:
  key: abcd123456789123456789123456789abcdabcd
  access-token-expiration-minutes: 30000
  refresh-token-expiration-minutes: 30000

  mail:
    host: smtp.gmail.com
    port: 587
    username: subgusals6650@gmail.com
    password: ${GOOGLE_CLIENT_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
mail:
  address:
    admin: admin@gmail.com

