#logging:
#  level:
#    org:
#      springframework:
#        web: debug
#    org.springframework.web.servlet: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace


cloud:
  aws:
    credentials:
      access-key: AKIAY6Z7EA6Y5R66ELJ3
      secret-key: 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
    s3:
      bucket: main22
    region:
      static: ap-northeast-2
    stack:
      auto: false


spring:
  #  servlet:
  #    multipart:
  #      max-file-size: 10MB
  #      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://main.cfjpwofewd2x.ap-northeast-2.rds.amazonaws.com:13306/main?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin
    password: admin123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 374180078488-v6mh6ruhpsr5ja2vnmghslqvf28jb2mg.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

#          kakao:
#            client-id: 2badaf984a50ed7e3b8f83534a70c397
#            redirect-uri: http://ec2-13-209-77-62.ap-northeast-2.compute.amazonaws.com/login/oauth2/kakao
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            scope: profile_nickname, account_email
#            client-name: Kakao
mail:
  address:
    admin: admin@admin
jwt:
  key: abcd123456789123456789123456789abcdabcd
  access-token-expiration-minutes: 480
  refresh-token-expiration-minutes: 900

image:
  upload:
    dir : classpath:/static/images/